export const CLINIC = {
  name: "Refine Clinic",
  tagline: "Beauty Redefined",
  phone1: "05399 42632",
  phone2: "07539 40219",
  whatsapp: "+212539942632",
  whatsappLink: "https://wa.me/212539942632",
  whatsappMessage: encodeURIComponent(
    "Bonjour, je souhaite prendre rendez-vous à Refine Clinic."
  ),
  email: "Contact@refineclinic.ma",
  website: "refineclinic.ma",
  instagram: "@refineclinic.tanger",
  instagramUrl: "https://instagram.com/refineclinic.tanger",
  address: {
    street: "Avenue Abi Al Hassan Echadli",
    building: "Centre Business Salman, 4ème étage, App.16",
    city: "Tanger",
    country: "Maroc",
    full: "Avenue Abi Al Hassan Echadli, Centre Business Salman, 4ème étage, App.16, Tanger",
    mapsUrl:
      "https://maps.google.com/?q=Avenue+Abi+Al+Hassan+Echadli+Tanger+Maroc",
  },
  hours: "Lundi – Samedi : 9h00 – 19h00",
  doctors: {
    meryem: {
      name: "Dr. El Boujadaini Meryem",
      nameAr: "د. مريم البوجدايني",
      title: "Médecin esthétique & Anti-âge — Lasers médicaux",
      slug: "dr-meryem",
      initials: "MB",
      image: "",
      treatments: [
        "Fillers (lèvres, visage, mâchoire)",
        "Botox",
        "Thread lift",
        "Épilation laser",
        "PRP",
        "Soins de peau",
      ],
    },
    amr: {
      name: "Dr. Amr Ismail",
      nameAr: "د. عمرو إسماعيل",
      title: "Chirurgien esthétique & Plastique",
      slug: "dr-amr",
      initials: "AI",
      image: "/images/doctors/dr-amr.jpg",
      treatments: [
        "Liposuccion / 4D Lipo",
        "Abdominoplastie (tummy tuck)",
        "Brachioplastie (lifting des bras)",
        "Lifting des cuisses",
        "Gynécomastie",
        "Otoplastie (chirurgie des oreilles)",
        "Blépharoplastie (chirurgie des paupières)",
        "Mammoplastie",
      ],
    },
  },
  // Body areas used for filtering and display
  areas: [
    "front", "yeux", "nez", "levres", "cou", "machoire", "oreilles",
    "corps", "ventre", "bras", "cuisses", "jambes", "mains",
    "aisselles", "cheveux", "poitrine", "dos",
  ] as const,
  services: [
    // ── Aesthetic Medicine — Dr. Meryem ──
    {
      slug: "botox",
      nameKey: "botox",
      icon: "Syringe",
      color: "#A65D46",
      category: "aesthetic",
      filterType: "injectable",
      area: ["front", "yeux", "nez", "levres", "cou", "machoire", "aisselles", "mains"],
      doctor: "meryem",
      image: "/images/services/botox.jpg",
      beforeAfter: { before: "/images/before-after/botox/before-1.jpg", after: "/images/before-after/botox/after-1.jpg" },
      indications: [
        "wrinkles_forehead", "glabellar_frown", "crows_feet", "eyebrow_lift",
        "bunny_lines", "nasal_tip_lift", "nasal_flare", "oral_commissures",
        "lip_lift", "smokers_lines", "gummy_smile", "marionette_lines",
        "dimpled_chin", "nefertiti_neck", "masseter", "platysmal_bands",
        "necklace_lines", "axillary_hyperhidrosis", "palmoplantar_hyperhidrosis",
      ],
    },
    {
      slug: "fillers",
      nameKey: "fillers",
      icon: "Droplet",
      color: "#8C736A",
      category: "aesthetic",
      filterType: "injectable",
      area: ["levres", "front", "yeux", "cou", "machoire", "mains"],
      doctor: "meryem",
      image: "/images/services/fillers.jpg",
      beforeAfter: { before: "/images/before-after/fillers/before-1.jpg", after: "/images/before-after/fillers/after-1.jpg" },
      indications: [
        "nasolabial_folds", "marionette_lines", "lip_filler", "smokers_lines",
        "tear_trough", "sunken_temples", "fine_wrinkles", "cheek_augmentation",
        "chin_augmentation", "texas_inject", "aging_hands",
      ],
    },
    {
      slug: "fils-tenseurs",
      nameKey: "threads",
      icon: "GitBranch",
      color: "#D9BBA9",
      category: "aesthetic",
      filterType: "injectable",
      area: ["front", "machoire", "cou"],
      doctor: "meryem",
      image: "/images/services/fils-tenseurs.jpg",
      indications: [],
    },
    {
      slug: "prp",
      nameKey: "prp",
      icon: "Droplets",
      color: "#D9BBA9",
      category: "aesthetic",
      filterType: "injectable",
      area: ["front", "yeux", "cou", "mains", "cheveux", "corps"],
      doctor: "meryem",
      image: "/images/services/prp.jpg",
      indications: [
        "hair_loss", "skin_rejuvenation_face", "skin_rejuvenation_neck",
        "skin_rejuvenation_hands", "stretch_marks", "dark_circles", "acne_scars",
      ],
    },
    {
      slug: "epilation-laser",
      nameKey: "laser",
      icon: "Zap",
      color: "#A65D46",
      category: "aesthetic",
      filterType: "soins",
      area: ["front", "corps", "jambes", "aisselles", "bras"],
      doctor: "meryem",
      image: "/images/services/epilation-laser.jpg",
      indications: ["hair_reduction", "vascular_lesions"],
    },
    {
      slug: "soin-visage",
      nameKey: "face",
      icon: "Sparkles",
      color: "#8C736A",
      category: "aesthetic",
      filterType: "soins",
      area: ["front", "yeux", "cou"],
      doctor: "meryem",
      image: "/images/services/soin-visage.jpg",
      beforeAfter: { before: "/images/before-after/soin-visage/before-1.jpg", after: "/images/before-after/soin-visage/after-1.jpg" },
      indications: [],
    },
    {
      slug: "peeling-chimique",
      nameKey: "peeling",
      icon: "Droplets",
      color: "#D9BBA9",
      category: "aesthetic",
      filterType: "soins",
      area: ["front", "cou"],
      doctor: "meryem",
      image: "/images/services/peeling-chimique.jpg",
      beforeAfter: { before: "/images/before-after/peeling-chimique/before-1.jpg", after: "/images/before-after/peeling-chimique/after-1.jpg" },
      indications: [],
    },
    {
      slug: "mesotherapie",
      nameKey: "meso",
      icon: "Activity",
      color: "#A65D46",
      category: "aesthetic",
      filterType: "injectable",
      area: ["front", "cheveux", "corps", "ventre", "bras", "cuisses", "dos"],
      doctor: "meryem",
      image: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=600&h=400&fit=crop&q=80",
      indications: [
        "meso_hair_loss", "meso_skin_rejuvenation", "meso_double_chin",
        "meso_love_handles", "meso_back_fat", "meso_arms",
        "meso_stomach", "meso_inner_thighs",
      ],
    },
    {
      slug: "traitement-cellulite",
      nameKey: "cellulite",
      icon: "Layers",
      color: "#8C736A",
      category: "aesthetic",
      filterType: "soins",
      area: ["cuisses", "ventre", "bras"],
      doctor: "meryem",
      image: "/images/services/traitement-cellulite.jpg",
      indications: [],
    },
    {
      slug: "soin-corps",
      nameKey: "body",
      icon: "Heart",
      color: "#D9BBA9",
      category: "aesthetic",
      filterType: "soins",
      area: ["corps", "jambes", "bras"],
      doctor: "meryem",
      image: "https://images.unsplash.com/photo-1519823551278-64ac92734fb1?w=600&h=400&fit=crop&q=80",
      indications: [],
    },
    // ── Plastic Surgery — Dr. Amr ──
    {
      slug: "liposuccion",
      nameKey: "liposuccion",
      icon: "Scissors",
      color: "#A65D46",
      category: "surgery",
      filterType: "chirurgie",
      area: ["ventre", "cuisses", "bras", "dos", "machoire"],
      doctor: "amr",
      image: "https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=600&h=400&fit=crop&q=80",
      beforeAfter: { before: "/images/before-after/liposuccion/before-1.jpg", after: "/images/before-after/liposuccion/after-1.jpg" },
      indications: [],
    },
    {
      slug: "abdominoplastie",
      nameKey: "abdominoplastie",
      icon: "Shield",
      color: "#8C736A",
      category: "surgery",
      filterType: "chirurgie",
      area: ["ventre"],
      doctor: "amr",
      image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&h=400&fit=crop&q=80",
      indications: [],
    },
    {
      slug: "brachioplastie",
      nameKey: "brachioplastie",
      icon: "Move",
      color: "#D9BBA9",
      category: "surgery",
      filterType: "chirurgie",
      area: ["bras"],
      doctor: "amr",
      image: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=600&h=400&fit=crop&q=80",
      beforeAfter: { before: "/images/before-after/brachioplastie/before-1.jpg", after: "/images/before-after/brachioplastie/after-1.jpg" },
      indications: [],
    },
    {
      slug: "lifting-cuisses",
      nameKey: "lifting_cuisses",
      icon: "TrendingUp",
      color: "#A65D46",
      category: "surgery",
      filterType: "chirurgie",
      area: ["cuisses"],
      doctor: "amr",
      image: "https://images.unsplash.com/photo-1519823551278-64ac92734fb1?w=600&h=400&fit=crop&q=80",
      indications: [],
    },
    {
      slug: "gynecomastie",
      nameKey: "gynecomastie",
      icon: "User",
      color: "#8C736A",
      category: "surgery",
      filterType: "chirurgie",
      area: ["poitrine"],
      doctor: "amr",
      image: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=600&h=400&fit=crop&q=80",
      indications: [],
    },
    {
      slug: "otoplastie",
      nameKey: "otoplastie",
      icon: "Ear",
      color: "#D9BBA9",
      category: "surgery",
      filterType: "chirurgie",
      area: ["oreilles"],
      doctor: "amr",
      image: "https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?w=600&h=400&fit=crop&q=80",
      indications: [],
    },
    {
      slug: "blepharoplastie",
      nameKey: "blepharoplastie",
      icon: "Eye",
      color: "#A65D46",
      category: "surgery",
      filterType: "chirurgie",
      area: ["yeux"],
      doctor: "amr",
      image: "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=600&h=400&fit=crop&q=80",
      indications: [],
    },
    {
      slug: "mammoplastie",
      nameKey: "mammoplastie",
      icon: "Heart",
      color: "#8C736A",
      category: "surgery",
      filterType: "chirurgie",
      area: ["poitrine"],
      doctor: "amr",
      image: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=600&h=400&fit=crop&q=80",
      indications: [],
    },
  ],
} as const;
