export const CLINIC = {
  name: "Refine Clinic",
  tagline: "Beauty Redefined",
  phone1: "05399 42632",
  phone2: "07539 40219",
  whatsapp: "+212539942632",
  whatsappLink: "https://wa.me/212539942632",
  whatsappMessage: encodeURIComponent(
    "Bonjour, je souhaite prendre rendez-vous à Refine Clinic."
  ),
  email: "Contact@refineclinic.ma",
  website: "refineclinic.ma",
  instagram: "@refineclinic.tanger",
  instagramUrl: "https://instagram.com/refineclinic.tanger",
  address: {
    street: "Avenue Abi Al Hassan Echadli",
    building: "Centre Business Salman, 4ème étage, App.16",
    city: "Tanger",
    country: "Maroc",
    full: "Avenue Abi Al Hassan Echadli, Centre Business Salman, 4ème étage, App.16, Tanger",
    mapsUrl:
      "https://maps.google.com/?q=Avenue+Abi+Al+Hassan+Echadli+Tanger+Maroc",
  },
  hours: "Lundi – Samedi : 9h00 – 19h00",
  doctors: {
    meryem: {
      name: "Dr. El Boujadaini Meryem",
      nameAr: "د. مريم البوجدايني",
      title: "Médecin esthétique & Anti-âge — Lasers médicaux",
      slug: "dr-meryem",
      initials: "MB",
      image: "",
      treatments: [
        "Fillers (lèvres, visage, mâchoire)",
        "Botox",
        "Thread lift",
        "Épilation laser",
        "PRP",
        "Soins de peau",
      ],
    },
    amr: {
      name: "Dr. Amr Ismail",
      nameAr: "د. عمرو إسماعيل",
      title: "Chirurgien esthétique & Plastique",
      slug: "dr-amr",
      initials: "AI",
      image: "/images/doctors/dr-amr.jpg",
      treatments: [
        "Liposuccion / 4D Lipo",
        "Abdominoplastie (tummy tuck)",
        "Brachioplastie (lifting des bras)",
        "Lifting des cuisses",
        "Gynécomastie",
        "Otoplastie (chirurgie des oreilles)",
        "Blépharoplastie (chirurgie des paupières)",
        "Mammoplastie",
      ],
    },
  },
  services: [
    // Aesthetic Medicine — Dr. Meryem
    {
      slug: "botox",
      nameKey: "botox",
      icon: "Syringe",
      color: "#A65D46",
      category: "aesthetic",
      filterType: "injectable",
      area: ["visage"],
      doctor: "meryem",
      image: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=600&h=400&fit=crop&q=80",
    },
    {
      slug: "fillers",
      nameKey: "fillers",
      icon: "Droplet",
      color: "#8C736A",
      category: "aesthetic",
      filterType: "injectable",
      area: ["visage"],
      doctor: "meryem",
      image: "https://images.unsplash.com/photo-1629909613654-28e377c37b09?w=600&h=400&fit=crop&q=80",
    },
    {
      slug: "fils-tenseurs",
      nameKey: "threads",
      icon: "GitBranch",
      color: "#D9BBA9",
      category: "aesthetic",
      filterType: "injectable",
      area: ["visage"],
      doctor: "meryem",
      image: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=600&h=400&fit=crop&q=80",
    },
    {
      slug: "epilation-laser",
      nameKey: "laser",
      icon: "Zap",
      color: "#A65D46",
      category: "aesthetic",
      filterType: "soins",
      area: ["corps"],
      doctor: "meryem",
      image: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=600&h=400&fit=crop&q=80",
    },
    {
      slug: "soin-visage",
      nameKey: "face",
      icon: "Sparkles",
      color: "#8C736A",
      category: "aesthetic",
      filterType: "soins",
      area: ["visage"],
      doctor: "meryem",
      image: "https://images.unsplash.com/photo-1616394584738-fc6e612e71b9?w=600&h=400&fit=crop&q=80",
    },
    {
      slug: "peeling-chimique",
      nameKey: "peeling",
      icon: "Droplets",
      color: "#D9BBA9",
      category: "aesthetic",
      filterType: "soins",
      area: ["visage"],
      doctor: "meryem",
      image: "https://images.unsplash.com/photo-1512290923902-8a9f81dc236c?w=600&h=400&fit=crop&q=80",
    },
    {
      slug: "mesotherapie",
      nameKey: "meso",
      icon: "Activity",
      color: "#A65D46",
      category: "aesthetic",
      filterType: "injectable",
      area: ["visage", "corps"],
      doctor: "meryem",
      image: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=600&h=400&fit=crop&q=80",
    },
    {
      slug: "traitement-cellulite",
      nameKey: "cellulite",
      icon: "Layers",
      color: "#8C736A",
      category: "aesthetic",
      filterType: "soins",
      area: ["corps"],
      doctor: "meryem",
      image: "https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=600&h=400&fit=crop&q=80",
    },
    {
      slug: "soin-corps",
      nameKey: "body",
      icon: "Heart",
      color: "#D9BBA9",
      category: "aesthetic",
      filterType: "soins",
      area: ["corps"],
      doctor: "meryem",
      image: "https://images.unsplash.com/photo-1519823551278-64ac92734fb1?w=600&h=400&fit=crop&q=80",
    },
    // Plastic Surgery — Dr. Amr
    {
      slug: "liposuccion",
      nameKey: "liposuccion",
      icon: "Scissors",
      color: "#A65D46",
      category: "surgery",
      filterType: "chirurgie",
      area: ["corps"],
      doctor: "amr",
      image: "https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=600&h=400&fit=crop&q=80",
    },
    {
      slug: "abdominoplastie",
      nameKey: "abdominoplastie",
      icon: "Shield",
      color: "#8C736A",
      category: "surgery",
      filterType: "chirurgie",
      area: ["corps"],
      doctor: "amr",
      image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&h=400&fit=crop&q=80",
    },
    {
      slug: "brachioplastie",
      nameKey: "brachioplastie",
      icon: "Move",
      color: "#D9BBA9",
      category: "surgery",
      filterType: "chirurgie",
      area: ["corps"],
      doctor: "amr",
      image: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=600&h=400&fit=crop&q=80",
    },
    {
      slug: "lifting-cuisses",
      nameKey: "lifting_cuisses",
      icon: "TrendingUp",
      color: "#A65D46",
      category: "surgery",
      filterType: "chirurgie",
      area: ["corps"],
      doctor: "amr",
      image: "https://images.unsplash.com/photo-1519823551278-64ac92734fb1?w=600&h=400&fit=crop&q=80",
    },
    {
      slug: "gynecomastie",
      nameKey: "gynecomastie",
      icon: "User",
      color: "#8C736A",
      category: "surgery",
      filterType: "chirurgie",
      area: ["corps"],
      doctor: "amr",
      image: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=600&h=400&fit=crop&q=80",
    },
    {
      slug: "otoplastie",
      nameKey: "otoplastie",
      icon: "Ear",
      color: "#D9BBA9",
      category: "surgery",
      filterType: "chirurgie",
      area: ["visage"],
      doctor: "amr",
      image: "https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?w=600&h=400&fit=crop&q=80",
    },
    {
      slug: "blepharoplastie",
      nameKey: "blepharoplastie",
      icon: "Eye",
      color: "#A65D46",
      category: "surgery",
      filterType: "chirurgie",
      area: ["visage"],
      doctor: "amr",
      image: "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=600&h=400&fit=crop&q=80",
    },
    {
      slug: "mammoplastie",
      nameKey: "mammoplastie",
      icon: "Heart",
      color: "#8C736A",
      category: "surgery",
      filterType: "chirurgie",
      area: ["corps"],
      doctor: "amr",
      image: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=600&h=400&fit=crop&q=80",
    },
  ],
} as const;
